/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Earth.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Model(props) {
    const { nodes, materials } = useGLTF('/Earth.glb')

    // spin the model
    // const modelRef = useRef(null);
    // useFrame(() => {
    //     if (modelRef.current) {
    //         modelRef.current.rotation.y += 0.01;
    //         // modelRef.current.rotation.x += 0.01;
    //         // modelRef.current.rotation.z += 0.01;
    //     }
    // });

    return (
    <group {...props} dispose={null}>
        <mesh geometry={nodes.Sphere002_1.geometry} material={materials['02___Default']} />
        <mesh geometry={nodes.Sphere002_1_1.geometry} material={materials._crayfishdiffuse} />
        <mesh geometry={nodes.Sphere002_1_2.geometry} material={materials['03___Default']} />
    </group>
    )
}

useGLTF.preload('/Earth.glb')
